apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    environment: dev
    name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    stdin: false
    tty: false
    envFrom:
      - configMapRef:
          name: mops
